FROM alpine:latest

ENV HOME /root
CMD [ "bash" ]

RUN apk upgrade -a

# GNU tools (alpine is based on busybox and musl instead of GNU)
RUN apk add \
  binutils coreutils file musl-dev musl-obstack-dev musl-nscd-dev argp-standalone

# Compiler and other related tools
RUN apk add \
  make autoconf autoconf-archive automake libtool \
  meson \
  pkgconf gcc gperf

# Test tools
RUN apk add \
  check-dev \
  bats \
  valgrind

# Libraries
RUN apk add \
  libconfig-dev

# Binaries required to build distribution archives
RUN apk add \
  gzip zip xz


# Compile logc
RUN apk add \
  git ca-certificates
RUN \
  git clone --branch "v0.4.0" "https://gitlab.nic.cz/turris/logc.git" && \
  cd logc && \
  ./bootstrap && ./configure --prefix=/usr && make install && \
  cd .. && \
  rm -rf logc
