# Wee need unstable for now because of check version
FROM debian:unstable as base

ENV HOME /root
CMD [ "bash" ]

RUN apt-get update && apt-get -y upgrade

# Compiler and other related tools
RUN apt-get update && apt-get -y install --no-install-recommends \
  make autoconf autoconf-archive automake libtool \
  meson \
  pkg-config gcc gperf

# Test tools
RUN apt-get update && apt-get -y install --no-install-recommends \
  check \
  bats \
  valgrind
# Linters
RUN apt-get update && apt-get -y install --no-install-recommends \
  cppcheck flawfinder
# Code coverage
RUN apt-get update && apt-get -y install --no-install-recommends \
  lcov

# Libraries
RUN apt-get update && apt-get -y install --no-install-recommends \
  libconfig-dev

# Binaries required to build distribution archives
RUN apt-get update && apt-get -y install --no-install-recommends \
  zip xz-utils

RUN apt-get clean


FROM base as logc

# Compile logc
RUN apt-get update && apt-get -y install --no-install-recommends \
  git ca-certificates
RUN \
  git clone --branch "v0.4.0" "https://gitlab.nic.cz/turris/logc.git" && \
  cd logc && \
  ./bootstrap && ./configure --disable-tests --disable-linters --prefix=/usr && \
  make install && \
  cd .. && \
  rm -rf logc

RUN apt-get clean
